version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel_app
    container_name: laravel_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    command: sh -c "composer install && php artisan serve --host=0.0.0.0 --port=8000"
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - postgres_tests
    networks:
      - laravel

  postgres:
    image: postgres:16.2
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: lara_surveys
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - laravel

  postgres_tests:
    image: postgres:16.2
    container_name: postgres_tests
    restart: unless-stopped
    environment:
      POSTGRES_DB: lara_surveys_tests
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data_tests:/var/lib/postgresql/data
    networks:
      - laravel

  npm:
    image: node:18.17.0
    container_name: npm
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    command: sh -c "npm install && npm run dev"
    ports:
      - "5173:5173"
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  postgres_data:
  postgres_data_tests: